language: node_js

services:
  - docker

node_js:
  - 12

before_install:
  - docker build -t travidev -f Dockerfile.dev .
  - docker run -d -p 5000:3000 travidev
  - docker build -t traviprod -f Dockerfile .
  - docker run -d -p 5000:3000 traviprod
  - docker ps -a

install:
  - npm install
    
script:
  - npm test